import * as R from 'ramda';

const DECORATIONS = {
  Antidote: { skill: 'Poison Resistance', size: 1, rarity: 5 },
  Geology: { skill: 'Geologist', size: 1, rarity: 5 },
  'Heavy Artillery': { skill: 'Heavy Artillery', size: 1, rarity: 5 },
  Hungerless: { skill: 'Hunger Resistance', size: 1, rarity: 5 },
  Satiated: { skill: 'Free Meal', size: 1, rarity: 5 },
  Protection: { skill: 'Divine Blessing', size: 1, rarity: 5 },
  Meowster: { skill: 'Palico Rally', size: 1, rarity: 5 },
  Botany: { skill: 'Botanist', size: 1, rarity: 5 },
  'Tip Toe': { skill: 'Stealth', size: 1, rarity: 5 },
  Flight: { skill: 'Airborne', size: 1, rarity: 5 },
  Smoke: { skill: 'Sporepuff Expert', size: 1, rarity: 5 },
  Mirewalker: { skill: 'Aquatic Expert', size: 1, rarity: 5 },
  Specimen: { skill: 'Entomologist', size: 1, rarity: 5 },
  Miasma: { skill: 'Effluvia Resistance', size: 1, rarity: 5 },
  Scent: { skill: 'Scenthound', size: 1, rarity: 5 },
  Intimidator: { skill: 'Intimidator', size: 1, rarity: 5 },
  Crisis: { skill: 'Resuscitate', size: 1, rarity: 5 },
  Antipara: { skill: 'Paralysis Resistance', size: 1, rarity: 5 },
  Fortitude: { skill: 'Fortify', size: 1, rarity: 5 },
  'Water Res': { skill: 'Water Resistance', size: 1, rarity: 5 },
  Suture: { skill: 'Bleeding Resistance', size: 1, rarity: 5 },
  'Dragon Res': { skill: 'Dragon Resistance', size: 1, rarity: 5 },
  'Fire Res': { skill: 'Fire Resistance', size: 1, rarity: 5 },
  'Ice Res': { skill: 'Ice Resistance', size: 1, rarity: 5 },
  'Def Lock': { skill: 'Iron Skin', size: 1, rarity: 5 },
  'Thunder Res': { skill: 'Thunder Resistance', size: 1, rarity: 5 },
  Pep: { skill: 'Sleep Resistance', size: 1, rarity: 5 },
  Antiblast: { skill: 'Blast Resistance', size: 1, rarity: 5 },
  Gobbler: { skill: 'Speed Eating', size: 1, rarity: 6 },
  Physique: { skill: 'Constitution', size: 2, rarity: 6 },
  Blaze: { skill: 'Fire Attack', size: 1, rarity: 6 },
  Evasion: { skill: 'Evade Window', size: 2, rarity: 6 },
  Jumping: { skill: 'Evade Extender', size: 2, rarity: 6 },
  Sheath: { skill: 'Quick Sheath', size: 1, rarity: 6 },
  Friendship: { skill: 'Wide-Range', size: 1, rarity: 6 },
  Enduring: { skill: 'Item Prolonger', size: 1, rarity: 6 },
  Medicine: { skill: 'Recovery Up', size: 1, rarity: 6 },
  Grinder: { skill: 'Speed Sharpening', size: 1, rarity: 6 },
  Steadfast: { skill: 'Stun Resistance', size: 1, rarity: 6 },
  Bomber: { skill: 'Bombadier', size: 1, rarity: 6 },
  Recovery: { skill: 'Recovery Speed', size: 1, rarity: 6 },
  Slider: { skill: 'Affinity Sliding', size: 2, rarity: 6 },
  Defense: { skill: 'Defense Boost', size: 1, rarity: 6 },
  Stonethrower: { skill: 'Slinger Capacity', size: 1, rarity: 6 },
  Footing: { skill: 'Tremor Resistance', size: 2, rarity: 6 },
  Brace: { skill: 'Flinch Free', size: 3, rarity: 6 },
  'Wind Resist': { skill: 'Windproof', size: 2, rarity: 6 },
  Earplug: { skill: 'Earplugs', size: 3, rarity: 6 },
  Vitality: { skill: 'Health Boost', size: 1, rarity: 6 },
  Resistor: { skill: 'Blight Resistance', size: 1, rarity: 6 },
  Sonorous: { skill: 'Horn Maestro', size: 1, rarity: 6 },
  KO: { skill: 'Slugger', size: 2, rarity: 6 },
  Stream: { skill: 'Water Attack', size: 1, rarity: 6 },
  Frost: { skill: 'Ice Attack', size: 1, rarity: 6 },
  Bolt: { skill: 'Thunder Attack', size: 1, rarity: 6 },
  Dragon: { skill: 'Dragon Attack', size: 1, rarity: 6 },
  Venom: { skill: 'Poison Attack', size: 1, rarity: 6 },
  Poisoncoat: { skill: 'Poison Functionality', size: 3, rarity: 6 },
  Expert: { skill: 'Critical Eye', size: 1, rarity: 6 },
  Tenderizer: { skill: 'Weakness Exploit', size: 2, rarity: 6 },
  Destroyer: { skill: 'Partbreaker', size: 2, rarity: 6 },
  Elementless: { skill: 'Non-elemental Boost', size: 2, rarity: 6 },
  Drain: { skill: 'Stamina Thief', size: 1, rarity: 6 },
  Paracoat: { skill: 'Para Functionality', size: 3, rarity: 7 },
  Sharp: { skill: 'Protective Polish', size: 2, rarity: 7 },
  Shield: { skill: 'Guard Up', size: 2, rarity: 7 },
  Dragonseal: { skill: 'Elderseal Boost', size: 3, rarity: 7 },
  Trueshot: { skill: 'Special Ammo Boost', size: 1, rarity: 7 },
  Enhancer: { skill: 'Power Prolonger', size: 2, rarity: 7 },
  Forceshot: { skill: 'Normal Shots', size: 3, rarity: 7 },
  Furor: { skill: 'Resentment', size: 2, rarity: 7 },
  Potential: { skill: 'Heroics', size: 2, rarity: 7 },
  Paralyzer: { skill: 'Paralysis Attack', size: 1, rarity: 7 },
  Sleep: { skill: 'Sleep Attack', size: 1, rarity: 7 },
  Ironwall: { skill: 'Guard', size: 1, rarity: 7 },
  Refresh: { skill: 'Stamina Surge', size: 2, rarity: 7 },
  Blash: { skill: 'Blast Attack', size: 1, rarity: 7 },
  Sleepcoat: { skill: 'Sleep Functionality', size: 3, rarity: 7 },
  Blastcoat: { skill: 'Blast Functionality', size: 3, rarity: 7 },
  Throttle: { skill: 'Latent Power', size: 2, rarity: 7 },
  Challenger: { skill: 'Agitator', size: 2, rarity: 7 },
  Attack: { skill: 'Attack Boost', size: 1, rarity: 7 },
  Flawless: { skill: 'Peak Performance', size: 2, rarity: 7 },
  Magazine: { skill: 'Capacity Boost', size: 2, rarity: 7 },
  Mighty: { skill: 'Maximum Might', size: 2, rarity: 7 },
  Sprinter: { skill: 'Marathon Runner', size: 2, rarity: 8 },
  Critical: { skill: 'Critical Boost', size: 2, rarity: 8 },
  Artillery: { skill: 'Artillery', size: 1, rarity: 8 },
  Fungiform: { skill: 'Mushroomancer', size: 1, rarity: 8 },
  Release: { skill: 'Free Element/Ammo Up', size: 3, rarity: 8 },
  Spread: { skill: 'Spread/Power Shots', size: 3, rarity: 8 },
  Charger: { skill: 'Focus', size: 2, rarity: 8 },
  Handicraft: { skill: 'Handicraft', size: 3, rarity: 8 },
  'Mighty Bow': { skill: 'Bow Charge Plus', size: 2, rarity: 8 },
  "Mind's Eye": { skill: "Mind's Eye/Ballistics", size: 2, rarity: 8 },
  Draw: { skill: 'Critical Draw', size: 2, rarity: 8 },
  Pierce: { skill: 'Piercing Shots', size: 3, rarity: 8 }
};

export const DECORATION_LIST = R.map(
  name => ({ name, ...DECORATIONS[name] }),
  R.keys(DECORATIONS)
);

export default DECORATIONS;
